apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: redis-in-azure
spec:
  hosts:
    - doc-index-updater-dev.redis.cache.windows.net
  ports:
    - number: 6379
      name: tcp-port
      protocol: TCP
    - number: 6380
      name: https-port-for-tls-origination
      protocol: HTTPS
  resolution: DNS
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: redis-in-azure
spec:
  hosts:
    - doc-index-updater-dev.redis.cache.windows.net
  tcp:
    - match:
        - port: 6379
      route:
        - destination:
            host: doc-index-updater-dev.redis.cache.windows.net
            subset: tls-origination
            port:
              number: 6380
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: redis-in-azure
spec:
  host: doc-index-updater-dev.redis.cache.windows.net
  subsets:
    - name: tls-origination
      trafficPolicy:
        loadBalancer:
          simple: ROUND_ROBIN
        portLevelSettings:
          - port:
              number: 6380
            tls:
              mode: SIMPLE # initiates HTTPS when accessing doc-index-updater-dev.redis.cache.windows.net
