apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-medicines-api
  namespace: istio-system
spec:
  dnsNames:
    - medicines-api.non-prod.mhra.gov.uk
  secretName: cert-medicines-api
  issuerRef:
    name: production
    kind: ClusterIssuer
