resources:
  - sealed-secrets-key.yaml
  - ServiceAccount-sealed-secrets-controller.yaml
  - CustomResourceDefinition-sealedsecrets.bitnami.com.yaml
  - ClusterRole-secrets-unsealer.yaml
  - ClusterRoleBinding-sealed-secrets-controller.yaml
  - Role-sealed-secrets-key-admin.yaml
  - Role-sealed-secrets-service-proxier.yaml
  - RoleBinding-sealed-secrets-controller.yaml
  - RoleBinding-sealed-secrets-service-proxier.yaml
  - Deployment-sealed-secrets-controller.yaml
  - Service-sealed-secrets-controller.yaml
