apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: medicines-api
spec:
  hosts:
    - medicines-api.localhost
  gateways:
    - istio-system/istio-ingressgateway
  http:
    - route:
        - destination:
            port:
              number: 80
            host: medicines-api
