apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: search-creds
  namespace: medicines-api
spec:
  encryptedData:
    api_key: AgBexritjJ2+mOSlxI0qfyV/4fhD0k3miwCMODb0+WhLegeL7ia0734TREy51M8tshKyzfhhohTwcbUeHyx1D15CHsGSOXjOZ+G9YS/Raqit+pIj9I2NPBn8spSZiknnzDOHst6SYoyjtNEA4N+ToUamPNPMkoCMCs/y+lamInr4s1cz/pdjDVaDdfcAH4Qq/i7WxdRVGjG/Tsq/ppFOzDpXE7XV2LyDJJSGcgrwFxDUFlJe2eNQuiyqmFzLIuY1NOFSGYlblaD9M5hBv9rOFqGAzlMxbxf19h7OtSOEbXHj2JF67NYRpUxGmbihBWMoD6NfroY1EFioFAN5UhTs+NDkSL16sq/w2KNxhOgYuoM044OE95V+pvhJsEPjfr7QsHywZwmbLLTVIkNY1imQOFYUeN3pDjrPOxqRr7TrWl8C+HPA5iZyjpIv8ROBI6N0Sxsh08vezsW7wquT43t2xxlAglkcpRy2JiHu/HMj+AMHRRCyk81DbP9RRCnt0CSN139OMSfSAVvSqsSqawQdawLpL1PEJPP8tKIuM8d1fjjwm7jCgly1VEpUUQPiVH0jl4TytK9fOW77jNyzHCPHkXyVjj4jVE8sTjT4MNBSXmlZuhbjEheBtZPshHi/zEL8A1OkmTdpT2KX9ivur0Zu/P6CEnfOZHX8OC2fHBJv6+wquxIAyulWkbYGjeTNA8b59dtV13rna/U7n5d+wRZjrCBnl0DLs8codO+ksRpLdkNmUg==
  template:
    metadata:
      creationTimestamp: null
      name: search-creds
      namespace: medicines-api
